/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Atendente;

import ABProjeto.TelaLogin;
import Cidadão.TelaCadastroCidadão;
import Cidadão.TelaConsultarCidadão;
import Vacina.TelaConsultarVacinas;
import Cidadão.Cidadão;
import Vacina.TelaVacinas;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author gusta
 */
public class TelaAtendente extends javax.swing.JFrame {

    /**
     * Creates new form telas
     */
    public TelaAtendente() {
        initComponents();
        setIcon();
        VoltarAoMenuMenuItem.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        voltar = new javax.swing.JToggleButton();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        CadastrosCidadãoMenuItem = new javax.swing.JMenuItem();
        CadastrarVacinaMenuItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        ConultarVacinaMenuItem = new javax.swing.JMenuItem();
        ConsultarCidadãoMenuItem = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        SairDoSistemaMenuItem = new javax.swing.JMenuItem();
        VoltarAoMenuMenuItem = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(420, 330));
        getContentPane().setLayout(null);

        voltar.setText("←");
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });
        getContentPane().add(voltar);
        voltar.setBounds(20, 440, 43, 23);

        jButton5.setBackground(new java.awt.Color(0, 153, 204));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Zimagens/ConsultarVacina.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(110, 360, 100, 90);

        jButton4.setBackground(new java.awt.Color(0, 153, 204));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Zimagens/CadastrarVacina.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(110, 210, 100, 90);

        jButton1.setBackground(new java.awt.Color(0, 153, 204));
        jButton1.setForeground(new java.awt.Color(204, 204, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Zimagens/CadastrarCidadão.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(250, 210, 100, 90);

        jButton3.setBackground(new java.awt.Color(0, 153, 204));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Zimagens/ConsultarCidadão.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(250, 360, 100, 90);

        jButton2.setBackground(new java.awt.Color(0, 153, 204));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Zimagens/Relatorio.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(400, 360, 100, 90);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel2.setText("Cadastrar Vacina");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(110, 190, 100, 14);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel3.setText("Cadastrar Cidadão");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(250, 190, 110, 14);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel4.setText("Consultar Cidadão");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(250, 340, 140, 14);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel5.setText("Consultar Vacina");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(110, 340, 100, 14);

        jLabel6.setText(" Tela Relario");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(400, 340, 70, 14);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Zimagens/TelaMenu2_1.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1000, 480);

        jMenuBar1.setBackground(new java.awt.Color(0, 51, 51));
        jMenuBar1.setForeground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMenuBar1.setPreferredSize(new java.awt.Dimension(222, 30));
        jMenuBar1.setRequestFocusEnabled(false);

        jMenu1.setBackground(new java.awt.Color(0, 51, 51));
        jMenu1.setText("Cadastrar");

        CadastrosCidadãoMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Zimagens/CadastrarCidadãoMenu.png"))); // NOI18N
        CadastrosCidadãoMenuItem.setText("Cadastrar Cidadão");
        CadastrosCidadãoMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrosCidadãoMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(CadastrosCidadãoMenuItem);

        CadastrarVacinaMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Zimagens/CadastrarVacinaMenu.png"))); // NOI18N
        CadastrarVacinaMenuItem.setText("Cadastrar Vacina");
        CadastrarVacinaMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarVacinaMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(CadastrarVacinaMenuItem);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Consultar");

        ConultarVacinaMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Zimagens/ConsultarVacinaMenu.png"))); // NOI18N
        ConultarVacinaMenuItem.setText("Consultar Vacina");
        ConultarVacinaMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConultarVacinaMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(ConultarVacinaMenuItem);

        ConsultarCidadãoMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Zimagens/ConsultarCidadãoMenu.png"))); // NOI18N
        ConsultarCidadãoMenuItem.setText("Consultar Cidadão");
        ConsultarCidadãoMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarCidadãoMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(ConsultarCidadãoMenuItem);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Realatorio");

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Zimagens/RelatorioMenu.png"))); // NOI18N
        jMenuItem2.setText("Relatorio");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Sair");

        SairDoSistemaMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Zimagens/SairMenu.png"))); // NOI18N
        SairDoSistemaMenuItem.setText("Fechar Sistema");
        SairDoSistemaMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairDoSistemaMenuItemActionPerformed(evt);
            }
        });
        jMenu4.add(SairDoSistemaMenuItem);

        VoltarAoMenuMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Zimagens/VoltarMenu.png"))); // NOI18N
        VoltarAoMenuMenuItem.setText("Voltar ao menu");
        VoltarAoMenuMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarAoMenuMenuItemActionPerformed(evt);
            }
        });
        jMenu4.add(VoltarAoMenuMenuItem);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(1013, 547));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        this.setVisible(false);
        TelaLogin telas = new TelaLogin();
        telas.setVisible(true);
    }//GEN-LAST:event_voltarActionPerformed

    private void CadastrosCidadãoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrosCidadãoMenuItemActionPerformed
       this.setVisible(false);
        TelaCadastroCidadão cadastro = new TelaCadastroCidadão();
        cadastro.setVisible(true);
    }//GEN-LAST:event_CadastrosCidadãoMenuItemActionPerformed

    private void ConsultarCidadãoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarCidadãoMenuItemActionPerformed
    this.setVisible(false);
        TelaConsultarCidadão consultar = new TelaConsultarCidadão();
        consultar.setVisible(true);
    }//GEN-LAST:event_ConsultarCidadãoMenuItemActionPerformed

    private void CadastrarVacinaMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarVacinaMenuItemActionPerformed
    this.setVisible(false);
        TelaVacinas vacinas = new TelaVacinas();
        vacinas.setVisible(true);
    }//GEN-LAST:event_CadastrarVacinaMenuItemActionPerformed

    private void ConultarVacinaMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConultarVacinaMenuItemActionPerformed
    this.setVisible(false);
        TelaConsultarVacinas Vacina = new TelaConsultarVacinas();
        Vacina.setVisible(true);
    }//GEN-LAST:event_ConultarVacinaMenuItemActionPerformed

    private void SairDoSistemaMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairDoSistemaMenuItemActionPerformed
    this.setVisible(false);
    }//GEN-LAST:event_SairDoSistemaMenuItemActionPerformed

    private void VoltarAoMenuMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarAoMenuMenuItemActionPerformed
    }//GEN-LAST:event_VoltarAoMenuMenuItemActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.setVisible(false);
        TelaConsultarCidadão consulta = new TelaConsultarCidadão();
        consulta.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        TelaCadastroCidadão cadastro = new TelaCadastroCidadão();
        cadastro.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        this.setVisible(false);
        TelaConsultarVacinas Vacina = new TelaConsultarVacinas();
        Vacina.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.setVisible(false);
        TelaVacinas vacinas = new TelaVacinas();
        vacinas.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
        TelaRelatorio telas = new TelaRelatorio();
        telas.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        this.setVisible(false);
        TelaRelatorio telas = new TelaRelatorio();
        telas.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAtendente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAtendente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAtendente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAtendente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAtendente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem CadastrarVacinaMenuItem;
    private javax.swing.JMenuItem CadastrosCidadãoMenuItem;
    private javax.swing.JMenuItem ConsultarCidadãoMenuItem;
    private javax.swing.JMenuItem ConultarVacinaMenuItem;
    private javax.swing.JMenuItem SairDoSistemaMenuItem;
    private javax.swing.JMenuItem VoltarAoMenuMenuItem;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JToggleButton voltar;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
       setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Zimagens/unnamed.png")));
    }
}
