/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Atendente;

import Administrador.TelaAdministrador;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author gusta
 */
public class TelaConsultarAtendente extends javax.swing.JFrame {

    /**
     * Creates new form TelaConsultarAdministrador
     */
    public TelaConsultarAtendente() {
        initComponents();
        setIcon();
    }
    
        public String dataVindaDoMysql(String data){
            String dia = DataFormattedTextField.getText().substring(8, 10);
            String mes = DataFormattedTextField.getText().substring(5, 7);
            String ano = DataFormattedTextField.getText().substring(0, 4);
            String nascMysql = dia+"/"+mes+"/"+ano;
            return nascMysql;
    }
        public void atualizarData(){
            String dia = DataFormattedTextField.getText().substring(8, 10);
            String mes = DataFormattedTextField.getText().substring(5, 7);
            String ano = DataFormattedTextField.getText().substring(0, 4);
            String nascMysql = dia+"/"+mes+"/"+ano;
            DataFormattedTextField.setText(nascMysql);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        RgTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        nomeTextField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        voltar = new javax.swing.JToggleButton();
        jLabel10 = new javax.swing.JLabel();
        SenhaTextField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        IdTextField = new javax.swing.JTextField();
        DataFormattedTextField = new javax.swing.JFormattedTextField();
        RgFormattedTextField = new javax.swing.JFormattedTextField();
        UfComboBox = new javax.swing.JComboBox<>();
        BairroTextField = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        CidadeTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        NomeTextField = new javax.swing.JTextField();
        CEPFormattedTextField = new javax.swing.JFormattedTextField();
        CelularFormattedTextField = new javax.swing.JFormattedTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Nome Completo");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(450, 190, 110, 14);

        jLabel2.setText("Data de Nascimento");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(450, 230, 130, 14);

        RgTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RgTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(RgTextField);
        RgTextField.setBounds(570, 50, 159, 30);

        jLabel6.setText("RG");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(520, 50, 40, 30);

        jLabel4.setText("RG");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(450, 270, 40, 20);

        jLabel8.setText("Celular");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(450, 310, 90, 14);

        nomeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(nomeTextField);
        nomeTextField.setBounds(570, 180, 268, 30);

        jButton1.setText("Consultar Atendente");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(850, 590, 140, 60);

        jButton2.setText("Deletar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(750, 590, 80, 60);

        jButton3.setText("Atualizar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(650, 590, 80, 60);

        voltar.setText("←");
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });
        getContentPane().add(voltar);
        voltar.setBounds(20, 610, 50, 30);

        jLabel10.setText("Senha");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(450, 350, 80, 14);
        getContentPane().add(SenhaTextField);
        SenhaTextField.setBounds(570, 340, 200, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Informações:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(550, 90, 147, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("Informe o RG para pesquisar um cidadão.");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(450, 10, 401, 22);

        jLabel13.setText("ID");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(450, 150, 40, 14);
        getContentPane().add(IdTextField);
        IdTextField.setBounds(570, 140, 90, 30);

        try {
            DataFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(DataFormattedTextField);
        DataFormattedTextField.setBounds(570, 220, 200, 30);

        try {
            RgFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(RgFormattedTextField);
        RgFormattedTextField.setBounds(570, 260, 200, 30);

        UfComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione uma uf", "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        UfComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UfComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(UfComboBox);
        UfComboBox.setBounds(570, 540, 130, 30);
        getContentPane().add(BairroTextField);
        BairroTextField.setBounds(570, 500, 130, 30);

        jLabel14.setText("Bairro");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(450, 510, 100, 14);

        jLabel15.setText("UF");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(450, 550, 100, 14);
        getContentPane().add(CidadeTextField);
        CidadeTextField.setBounds(570, 420, 130, 30);

        jLabel9.setText("Cidade");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(450, 430, 100, 14);

        jLabel3.setText("Nome da rua");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(450, 470, 100, 14);
        getContentPane().add(NomeTextField);
        NomeTextField.setBounds(570, 460, 130, 30);

        try {
            CEPFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(CEPFormattedTextField);
        CEPFormattedTextField.setBounds(570, 380, 130, 30);

        try {
            CelularFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(CelularFormattedTextField);
        CelularFormattedTextField.setBounds(570, 300, 200, 30);

        jLabel16.setText("CEP");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(450, 390, 100, 14);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Zimagens/TelaMenuAdm.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 1010, 660);

        setSize(new java.awt.Dimension(1022, 698));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void RgTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RgTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RgTextFieldActionPerformed

    private void nomeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeTextFieldActionPerformed

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        this.setVisible(false);
        TelaAdministrador adm = new TelaAdministrador();
        adm.setVisible(true);
    }//GEN-LAST:event_voltarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    if (RgTextField.getText().equals("")){
        JOptionPane.showMessageDialog(null, "Informe o RG para pesquisar o atendente", "Algo deu errado", JOptionPane.ERROR_MESSAGE);
        return;
    }
    String RG = RgTextField.getText();
    Atendente p = new Atendente();
    p.setRG(RG);
    p = p.consulta();
    //idTextField.setText(p.getId());
    IdTextField.setText(p.getId());
    nomeTextField.setText(p.getNome());
    DataFormattedTextField.setText(p.getNasc());
    atualizarData();
    RgFormattedTextField.setText(p.getRG());
    CelularFormattedTextField.setText(p.getCelular());
    SenhaTextField.setText(p.getSenha());
    //endereçoTextField.setText(p.getEndereço());
    
    IdTextField.setEnabled(false);
    RgFormattedTextField.setEnabled(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
     if (RgTextField.getText().equals("")){
        JOptionPane.showMessageDialog(null, "Informe o RG para pesquisar o atendente", "Algo deu errado", JOptionPane.ERROR_MESSAGE);
        return;
    }if (IdTextField.getText().equals("")){
        JOptionPane.showMessageDialog(null, "Informe o ID para continuar", "Algo deu errado", JOptionPane.ERROR_MESSAGE);
        return;
    }if (nomeTextField.getText().equals("")){
        JOptionPane.showMessageDialog(null, "Informe o nome para continuar", "Algo deu errado", JOptionPane.ERROR_MESSAGE);
        return;
    }if (DataFormattedTextField.getText().equals("")){
        JOptionPane.showMessageDialog(null, "Informe a data de nascimento para continuar", "Algo deu errado", JOptionPane.ERROR_MESSAGE);
        return;
    }if (RgFormattedTextField.getText().equals("")){
        JOptionPane.showMessageDialog(null, "Informe o RG para continuar", "Algo deu errado", JOptionPane.ERROR_MESSAGE);
        return;
    }if (CelularFormattedTextField.getText().equals("")){
        JOptionPane.showMessageDialog(null, "Informe o numero para continuar", "Algo deu errado", JOptionPane.ERROR_MESSAGE);
        return;
    }if (SenhaTextField.getText().equals("")){
        JOptionPane.showMessageDialog(null, "Informe a senha para continuar", "Algo deu errado", JOptionPane.ERROR_MESSAGE);
        return;
    }if (CEPFormattedTextField.getText().equals("")){
        JOptionPane.showMessageDialog(null, "Informe a senha para continuar", "Algo deu errado", JOptionPane.ERROR_MESSAGE);
        return;
    }if (CidadeTextField.getText().equals("")){
        JOptionPane.showMessageDialog(null, "Informe a senha para continuar", "Algo deu errado", JOptionPane.ERROR_MESSAGE);
        return;
    }if (NomeTextField.getText().equals("")){
        JOptionPane.showMessageDialog(null, "Informe a senha para continuar", "Algo deu errado", JOptionPane.ERROR_MESSAGE);
        return;
    }if (BairroTextField.getText().equals("")){
        JOptionPane.showMessageDialog(null, "Informe a senha para continuar", "Algo deu errado", JOptionPane.ERROR_MESSAGE);
        return;
    }if (UfComboBox.getSelectedItem().equals("Selecione uma uf")){
        JOptionPane.showMessageDialog(null, "Informe a senha para continuar", "Algo deu errado", JOptionPane.ERROR_MESSAGE);
        return;
    }else{
        JOptionPane.showMessageDialog(null, "Cidadão atualiza com sucesso");
    }
        
        String nome = nomeTextField.getText();
        String nasc = DataFormattedTextField.getText();
        String RG = RgFormattedTextField.getText();
        String celular = CelularFormattedTextField.getText();
        String senha = SenhaTextField.getText();

        Atendente p = new Atendente();
        p.setNome(nome);
        p.setNasc(nasc);
        p.setRG(RG);
        p.setCelular(celular);
        p.setSenha(senha);
        p.atualizar();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (IdTextField.getText().equals("")){
        JOptionPane.showMessageDialog(null, "é necessario o id para excluir um atendente", "Algo deu errado", JOptionPane.ERROR_MESSAGE);
        return;
    } else{
        JOptionPane.showMessageDialog(null, "Atendente excluido com sucesso");
        }
        
        String id = IdTextField.getText();
        Atendente p = new Atendente();
        p.setId(id);
        p.Deletar();
        
        IdTextField.setText("");
        nomeTextField.setText("");
        DataFormattedTextField.setText("");
        RgFormattedTextField.setText("");
        CelularFormattedTextField.setText("");
        SenhaTextField.setText("");

    }//GEN-LAST:event_jButton2ActionPerformed

    private void UfComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UfComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UfComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaConsultarAtendente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaConsultarAtendente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaConsultarAtendente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaConsultarAtendente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaConsultarAtendente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BairroTextField;
    private javax.swing.JFormattedTextField CEPFormattedTextField;
    private javax.swing.JFormattedTextField CelularFormattedTextField;
    private javax.swing.JTextField CidadeTextField;
    private javax.swing.JFormattedTextField DataFormattedTextField;
    private javax.swing.JTextField IdTextField;
    private javax.swing.JTextField NomeTextField;
    private javax.swing.JFormattedTextField RgFormattedTextField;
    private javax.swing.JTextField RgTextField;
    private javax.swing.JTextField SenhaTextField;
    private javax.swing.JComboBox<String> UfComboBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nomeTextField;
    private javax.swing.JToggleButton voltar;
    // End of variables declaration//GEN-END:variables
private void setIcon() {
       setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Zimagens/unnamed.png")));
    }
}
