/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Atendente;

import Administrador.TelaAdministrador;
import Atendente.Atendente;
import Cidadão.MenssagemDeErro;
import java.awt.Color;
import java.awt.Toolkit;
import javax.swing.JOptionPane;



/**
 *
 * @author gusta
 */
public class TelaCadastrarAtendente extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastrarAtendente
     */
    public TelaCadastrarAtendente() {
        initComponents();
        setIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botaoCadastrar = new javax.swing.JButton();
        voltar = new javax.swing.JToggleButton();
        nomeAtendenteTextField = new javax.swing.JTextField();
        SenhaTextField = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        CidadeTextField = new javax.swing.JTextField();
        BairroTextField = new javax.swing.JTextField();
        RuaTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        DataFormattedTextField = new javax.swing.JFormattedTextField();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        FoneFormattedTextField = new javax.swing.JFormattedTextField();
        CepFormattedTextField = new javax.swing.JFormattedTextField();
        UfComboBox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        botaoCadastrar.setBackground(new java.awt.Color(102, 153, 255));
        botaoCadastrar.setText("Cadastrar");
        botaoCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(botaoCadastrar);
        botaoCadastrar.setBounds(880, 540, 120, 90);

        voltar.setText("←");
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });
        getContentPane().add(voltar);
        voltar.setBounds(20, 640, 43, 23);

        nomeAtendenteTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nomeAtendenteTextFieldFocusGained(evt);
            }
        });
        nomeAtendenteTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeAtendenteTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(nomeAtendenteTextField);
        nomeAtendenteTextField.setBounds(530, 120, 270, 30);

        SenhaTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                SenhaTextFieldFocusGained(evt);
            }
        });
        getContentPane().add(SenhaTextField);
        SenhaTextField.setBounds(530, 360, 270, 30);

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel21.setText("Insira as informações abaixo");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(520, 10, 306, 29);
        getContentPane().add(CidadeTextField);
        CidadeTextField.setBounds(530, 480, 130, 30);
        getContentPane().add(BairroTextField);
        BairroTextField.setBounds(670, 540, 130, 30);
        getContentPane().add(RuaTextField);
        RuaTextField.setBounds(670, 480, 130, 30);

        jLabel1.setText("Nome da rua");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(670, 460, 100, 14);

        jLabel2.setText("Nome completo");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(530, 100, 100, 14);

        jLabel4.setText("Data de nacimento");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(530, 160, 100, 14);

        jLabel5.setText("RG");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(530, 220, 100, 14);

        jLabel6.setText("Fone");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(530, 280, 100, 14);

        jLabel7.setText("Senha");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(530, 340, 100, 14);

        jLabel8.setText("CEP");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(530, 400, 100, 14);

        jLabel9.setText("Cidade");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(530, 460, 100, 14);

        jLabel10.setText("Bairro");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(670, 520, 100, 14);

        jLabel11.setText("UF");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(530, 520, 100, 14);

        try {
            DataFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(DataFormattedTextField);
        DataFormattedTextField.setBounds(530, 180, 270, 30);

        try {
            jFormattedTextField2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(jFormattedTextField2);
        jFormattedTextField2.setBounds(530, 240, 270, 30);

        try {
            FoneFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(FoneFormattedTextField);
        FoneFormattedTextField.setBounds(530, 300, 270, 30);

        try {
            CepFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(CepFormattedTextField);
        CepFormattedTextField.setBounds(530, 420, 270, 30);

        UfComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione uma uf", "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        getContentPane().add(UfComboBox);
        UfComboBox.setBounds(530, 540, 130, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Zimagens/TelaMenuAdm.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 1380, 675);

        jTextField1.setText("jTextField1");
        getContentPane().add(jTextField1);
        jTextField1.setBounds(670, 150, 60, 20);

        setSize(new java.awt.Dimension(1118, 712));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastrarActionPerformed
    
             if (nomeAtendenteTextField.getText().equals("")){
        JOptionPane.showMessageDialog(null, "Informe o nome para continuar", "Algo deu errado", JOptionPane.ERROR_MESSAGE);
        return;
    }if (DataFormattedTextField.getText().equals("  /  /    ")){
        JOptionPane.showMessageDialog(null, "Informe a data de nascimento para continuar", "Algo deu errado", JOptionPane.ERROR_MESSAGE);
        return;
    }if (jFormattedTextField2.getText().equals("  .   .   - ")){
        JOptionPane.showMessageDialog(null, "Informe o RG para continuar", "Algo deu errado", JOptionPane.ERROR_MESSAGE);
        return;
    }if (FoneFormattedTextField.getText().equals("(  )      -    ")){
        JOptionPane.showMessageDialog(null, "Informe o numero para continuar", "Algo deu errado", JOptionPane.ERROR_MESSAGE);
        return;
    }if (SenhaTextField.getText().equals("")){
        JOptionPane.showMessageDialog(null, "Informe a senha para continuar", "Algo deu errado", JOptionPane.ERROR_MESSAGE);
        return;
    }if (CepFormattedTextField.getText().equals("     -   ")){
        JOptionPane.showMessageDialog(null, "Informe o CEP para continuar", "Algo deu errado", JOptionPane.ERROR_MESSAGE);
        return;
    }if (CidadeTextField.getText().equals("")){
        JOptionPane.showMessageDialog(null, "Informe a cidade para continuar", "Algo deu errado", JOptionPane.ERROR_MESSAGE);
        return;
    }if (RuaTextField.getText().equals("")){
        JOptionPane.showMessageDialog(null, "Informe a rua para continuar", "Algo deu errado", JOptionPane.ERROR_MESSAGE);
        return;
    }if (BairroTextField.getText().equals("")){
        JOptionPane.showMessageDialog(null, "Informe o bairro para continuar", "Algo deu errado", JOptionPane.ERROR_MESSAGE);
        return;
    }if (UfComboBox.getSelectedItem().equals("Selecione uma uf")){
        JOptionPane.showMessageDialog(null, "Selecione uma uf para continuar", "Algo deu errado", JOptionPane.ERROR_MESSAGE);
        return;
    }else{
        JOptionPane.showMessageDialog(null, "Cidadão cadastrado com sucesso");
    }
    
        
    String nome = nomeAtendenteTextField.getText();
    String dia = DataFormattedTextField.getText().substring(0, 2);
    String mes = DataFormattedTextField.getText().substring(3, 5);
    String ano = DataFormattedTextField.getText().substring(6);
    String nasc = ano+"-"+mes+"-"+dia;
    String RG = jFormattedTextField2.getText();
    String celular = FoneFormattedTextField.getText();
    String senha = SenhaTextField.getText();
    //Codigo do endereço
    String rua = RuaTextField.getText();
    String CEP = CepFormattedTextField.getText();
    String cidade = CidadeTextField.getText();
    String bairro = BairroTextField.getText();
    String uf = (String) UfComboBox.getSelectedItem();
        try{
    ErroMenssagemAtendente atendente = new ErroMenssagemAtendente(RG);
    if(atendente.existeAtendete(atendente)){
    JOptionPane.showMessageDialog(null,"Atendente ja cadastrado", "Algo deu errado", JOptionPane.ERROR_MESSAGE);
    return;
    }

    }catch(Exception e){
        JOptionPane.showMessageDialog(null, "Problemas tecnicos. Tente novamente mais tarde");
        e.printStackTrace();
    }
    

        EndereçoAtendente ate = new EndereçoAtendente();
        ate.setRua(rua);
        ate.setCep(CEP);
        ate.setCidade(cidade);
        ate.setBairro(bairro);
        ate.setUf(uf);
        ate.inserirEndereçoAtendente();

        Atendente A = new Atendente();
        A.setNome(nome);
        A.setNasc(nasc);
        A.setRG(RG);       
        A.setCelular(celular);        
        A.setSenha(senha);
        A.Cadastrar();
        
    
    }//GEN-LAST:event_botaoCadastrarActionPerformed

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        this.setVisible(false);
        TelaAdministrador adm = new TelaAdministrador();
        adm.setVisible(true);
    }//GEN-LAST:event_voltarActionPerformed

    private void nomeAtendenteTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeAtendenteTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeAtendenteTextFieldActionPerformed

    private void nomeAtendenteTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nomeAtendenteTextFieldFocusGained

    }//GEN-LAST:event_nomeAtendenteTextFieldFocusGained

    private void SenhaTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SenhaTextFieldFocusGained

    }//GEN-LAST:event_SenhaTextFieldFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrarAtendente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrarAtendente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrarAtendente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrarAtendente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastrarAtendente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BairroTextField;
    private javax.swing.JFormattedTextField CepFormattedTextField;
    private javax.swing.JTextField CidadeTextField;
    private javax.swing.JFormattedTextField DataFormattedTextField;
    private javax.swing.JFormattedTextField FoneFormattedTextField;
    private javax.swing.JTextField RuaTextField;
    private javax.swing.JTextField SenhaTextField;
    private javax.swing.JComboBox<String> UfComboBox;
    private javax.swing.JButton botaoCadastrar;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField nomeAtendenteTextField;
    private javax.swing.JToggleButton voltar;
    // End of variables declaration//GEN-END:variables
private void setIcon() {
       setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Zimagens/unnamed.png")));
    }
}
