/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Administrador;

import Administrador.TelaAdministrador;
import Atendente.Atendente;
import Cidadão.Cidadão;
import java.awt.Color;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author gusta
 */
public class TelaCadastrarAdministrador extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastrarAdministrador
     */
    public TelaCadastrarAdministrador() {
        initComponents();
        setIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        voltar = new javax.swing.JToggleButton();
        BairroTextField = new javax.swing.JTextField();
        CidadeTextField = new javax.swing.JTextField();
        RuaTextField = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        SenhaAdministradorTextField = new javax.swing.JTextField();
        nomeAdministradorTextField = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        jFormattedTextField3 = new javax.swing.JFormattedTextField();
        jFormattedTextField4 = new javax.swing.JFormattedTextField();
        UfComboBox = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton1.setText("Cadastrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(860, 550, 130, 100);

        voltar.setText("←");
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });
        getContentPane().add(voltar);
        voltar.setBounds(20, 630, 43, 23);

        BairroTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BairroTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(BairroTextField);
        BairroTextField.setBounds(480, 610, 270, 30);
        getContentPane().add(CidadeTextField);
        CidadeTextField.setBounds(480, 550, 270, 30);

        RuaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RuaTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(RuaTextField);
        RuaTextField.setBounds(480, 370, 270, 30);

        jButton2.setText("Buscar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(760, 430, 70, 30);

        SenhaAdministradorTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                SenhaAdministradorTextFieldFocusGained(evt);
            }
        });
        getContentPane().add(SenhaAdministradorTextField);
        SenhaAdministradorTextField.setBounds(480, 310, 270, 30);

        nomeAdministradorTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nomeAdministradorTextFieldFocusGained(evt);
            }
        });
        nomeAdministradorTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeAdministradorTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(nomeAdministradorTextField);
        nomeAdministradorTextField.setBounds(480, 70, 270, 30);

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel21.setText("Insira as informações abaixo");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(450, 10, 306, 29);

        jButton3.setText("Limpar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(860, 510, 130, 30);

        jLabel2.setText("Nome completo");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(480, 50, 160, 14);

        jLabel4.setText("Data de nacimento");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(480, 110, 150, 14);

        jLabel5.setText("RG");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(480, 170, 100, 14);

        jLabel6.setText("Fone");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(480, 230, 100, 14);

        jLabel7.setText("Senha");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(480, 290, 100, 14);

        jLabel8.setText("CEP");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(480, 410, 100, 14);

        jLabel9.setText("Cidade");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(480, 530, 100, 14);

        jLabel11.setText("UF");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(480, 470, 100, 14);

        jLabel1.setText("Nome da rua");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(480, 350, 100, 14);

        try {
            jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(jFormattedTextField1);
        jFormattedTextField1.setBounds(480, 130, 270, 30);

        try {
            jFormattedTextField2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(jFormattedTextField2);
        jFormattedTextField2.setBounds(480, 190, 270, 30);

        try {
            jFormattedTextField3.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(jFormattedTextField3);
        jFormattedTextField3.setBounds(480, 250, 270, 30);

        try {
            jFormattedTextField4.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(jFormattedTextField4);
        jFormattedTextField4.setBounds(480, 430, 270, 30);

        UfComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        getContentPane().add(UfComboBox);
        UfComboBox.setBounds(480, 490, 130, 30);

        jLabel10.setText("Bairro");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(480, 590, 100, 14);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Zimagens/TelaMenuAdm.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 1020, 670);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Zimagens/TelaMenuAdm.png"))); // NOI18N
        jLabel12.setText("jLabel3");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(0, 0, 1380, 675);

        jTextField1.setText("jTextField1");
        getContentPane().add(jTextField1);
        jTextField1.setBounds(520, 120, 60, 20);

        setSize(new java.awt.Dimension(1036, 708));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        //Passar de para outras telas
        this.setVisible(false);
        TelaAdministrador adm = new TelaAdministrador();
        adm.setVisible(true);
    }//GEN-LAST:event_voltarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

    }//GEN-LAST:event_jButton2ActionPerformed

    private void nomeAdministradorTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeAdministradorTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeAdministradorTextFieldActionPerformed

    private void nomeAdministradorTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nomeAdministradorTextFieldFocusGained

    }//GEN-LAST:event_nomeAdministradorTextFieldFocusGained

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String nome = nomeAdministradorTextField.getText();
        String nasc = jFormattedTextField1.getText();
        String RG = jFormattedTextField2.getText();
        String celular = jFormattedTextField3.getText();
        String senha = SenhaAdministradorTextField.getText();

        
        Administrador p = new Administrador ();
        if (nomeAdministradorTextField.getText().equals("")){
        JOptionPane.showMessageDialog(null,"Insisa um nome valido.", "Algo deu errado", JOptionPane.ERROR_MESSAGE);
        return;
        }
        
        if (jFormattedTextField1.getText().equals("")){
        JOptionPane.showMessageDialog(null,"Insisa uma data de nacimento valido.", "Algo deu errado", JOptionPane.ERROR_MESSAGE);
        return;
        }

        if (jFormattedTextField2.getText().equals("")){
        JOptionPane.showMessageDialog(null,"Insisa um CPF valido.", "Algo deu errado", JOptionPane.ERROR_MESSAGE);
        return;
        }

        if (jFormattedTextField3.getText().equals("")){
        JOptionPane.showMessageDialog(null,"Insisa um Numero valido.", "Algo deu errado", JOptionPane.ERROR_MESSAGE);
        return;
        }

        if (SenhaAdministradorTextField.getText().equals("")){
        JOptionPane.showMessageDialog(null,"Insisa uma senha valida.", "Algo deu errado", JOptionPane.ERROR_MESSAGE);
        return;
        }
        
    try{
    TelaErroAdm adm = new TelaErroAdm(RG);
       if(adm.existe(adm)){
       JOptionPane.showMessageDialog(null,"Cidadão ja castrado.", "Algo deu errado", JOptionPane.ERROR_MESSAGE);
       return;
       }else{
       JOptionPane.showMessageDialog(null, "O usuario foi cadastrado com sucesso");
       }
       }catch(Exception e){
        JOptionPane.showMessageDialog(null, "Problemas tecnicos. Tente novamente mais tarde");
        e.printStackTrace();
        }
    
        p.setNome(nome);
        p.setRg(RG);
        p.setCelular(celular);
        p.setNasc(nasc);
        p.setSenha(senha);
        p.inserir();
       
    
    //idTextField.setText(p.getId());

        nomeAdministradorTextField.getText();
        jFormattedTextField1.setText(p.getNasc());
        jFormattedTextField2.setText(p.getRg());
        jFormattedTextField3.setText(p.getCelular());
        SenhaAdministradorTextField.setText(p.getCelular());

    }//GEN-LAST:event_jButton1ActionPerformed

    private void SenhaAdministradorTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SenhaAdministradorTextFieldFocusGained

    }//GEN-LAST:event_SenhaAdministradorTextFieldFocusGained

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

    }//GEN-LAST:event_jButton3ActionPerformed

    private void BairroTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BairroTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BairroTextFieldActionPerformed

    private void RuaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RuaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RuaTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrarAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrarAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrarAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrarAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastrarAdministrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BairroTextField;
    private javax.swing.JTextField CidadeTextField;
    private javax.swing.JTextField RuaTextField;
    private javax.swing.JTextField SenhaAdministradorTextField;
    private javax.swing.JComboBox<String> UfComboBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JFormattedTextField jFormattedTextField3;
    private javax.swing.JFormattedTextField jFormattedTextField4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField nomeAdministradorTextField;
    private javax.swing.JToggleButton voltar;
    // End of variables declaration//GEN-END:variables
private void setIcon() {
       setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Zimagens/unnamed.png")));
    }
}
