/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Cidadão;

import Vacina.Vacina;
import java.awt.Toolkit;
import java.time.LocalDate;
import javax.swing.JOptionPane;

/**
 *
 * @author gusta
 */
public class TelaVacinação extends javax.swing.JFrame {

    /**
     * Creates new form TelaVacinação
     */
    public TelaVacinação() {
        initComponents();
        
    LocalDate hoje = LocalDate.now();
    jTextField1.setText("" + hoje);  
    
    NomesVacinasComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new Vacina().ListarNomeVacina()));
    setLocationRelativeTo(null);
    setIcon();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        NomesVacinasComboBox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        diasField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton4.setText("Pesquisar dias");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(220, 240, 130, 41);

        jButton1.setText("Gerar data");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(60, 240, 130, 41);

        jLabel15.setText("Nome da vacina utilizada:");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(50, 180, 150, 14);

        NomesVacinasComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione uma vacina", "" }));
        NomesVacinasComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomesVacinasComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(NomesVacinasComboBox);
        NomesVacinasComboBox.setBounds(220, 170, 128, 32);

        jLabel2.setText("DIAS");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(270, 120, 39, 14);
        getContentPane().add(diasField);
        diasField.setBounds(220, 110, 44, 35);

        jLabel1.setText("Intervalo entre doses:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 120, 150, 14);

        jLabel14.setText("Dia da próxima Vacinação:");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(50, 70, 140, 14);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(220, 70, 111, 29);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(220, 20, 110, 28);

        jLabel13.setText("Data que foi vacinado:");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(50, 30, 140, 14);

        setSize(new java.awt.Dimension(410, 357));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String nome = (String) NomesVacinasComboBox.getSelectedItem();
        Cidadão pes = new Cidadão();
        pes.setNome(nome);
        pes = pes.consultaIntervalo();
        //idTextField.setText(p.getId());
        diasField.setText(pes.getIntervalo());
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        LocalDate hoje = LocalDate.now();

        String data = diasField.getText();

        Cidadão pes = new Cidadão();
        LocalDate proximaData = hoje.plusDays(Long.parseLong(diasField.getText()));

        jTextField3.setText(""+proximaData);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed

    }//GEN-LAST:event_jTextField1ActionPerformed

    private void NomesVacinasComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomesVacinasComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomesVacinasComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaVacinação.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaVacinação.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaVacinação.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaVacinação.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaVacinação().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> NomesVacinasComboBox;
    private javax.swing.JTextField diasField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
private void setIcon() {
       setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Zimagens/unnamed.png")));
    }
}
