/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Cidadão;

import Cidadão.Cidadão;
import Atendente.TelaAtendente;
import Atendente.TelaConsultarAtendente;
import Atendente.TelaRelatorio;
import Vacina.TelaConsultarVacinas;
import Vacina.TelaVacinas;
import Vacina.Vacina;
import java.awt.Toolkit;
import java.sql.Date;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.Month;
import java.time.Period;
import java.time.format.DateTimeFormatter;
import java.time.format.FormatStyle;
import javax.swing.JOptionPane;


/**
 *
 * @author gusta
 */
public class TelaConsultarCidadão extends javax.swing.JFrame {

    /**
     * Creates new form TelaConsultarUsuario
     */
    public TelaConsultarCidadão() {
        initComponents();
        nomesVacinaComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new Vacina().ListarNomeVacina()));
    setLocationRelativeTo(null);
    setIcon();
    ConsultarCidadãoMenuItem.setEnabled(false);
    jButton6.setEnabled(false);
    CodigoTextField2.setEnabled(false);
    }
    public String dataVindaDoMysql(String data){
            String dia = NascTextField.getText().substring(8, 10);
            String mes = NascTextField.getText().substring(5, 7);
            String ano = NascTextField.getText().substring(0, 4);
            String nascMysql = dia+"/"+mes+"/"+ano;
            return nascMysql;
    }
        public void atualizarData(){
            String dia = NascTextField.getText().substring(8, 10);
            String mes = NascTextField.getText().substring(5, 7);
            String ano = NascTextField.getText().substring(0, 4);
            String nascMysql = dia+"/"+mes+"/"+ano;
            NascTextField.setText(nascMysql);
    }
        
        public String dataVindaDoMysqlDois(String data){
            String dia = PrimeiraTextField.getText().substring(8, 10);
            String mes = PrimeiraTextField.getText().substring(5, 7);
            String ano = PrimeiraTextField.getText().substring(0, 4);
            String nascMysql = dia+"/"+mes+"/"+ano;
            return nascMysql;
    }
        public void atualizarDataDois(){
            String dia = PrimeiraTextField.getText().substring(8, 10);
            String mes = PrimeiraTextField.getText().substring(5, 7);
            String ano = PrimeiraTextField.getText().substring(0, 4);
            String nascMysql = dia+"/"+mes+"/"+ano;
            PrimeiraTextField.setText(nascMysql);
    }
            public String dataVindaDoMysqlTres(String data){
            String dia = SegundaFormattedTextField1.getText().substring(8, 10);
            String mes = SegundaFormattedTextField1.getText().substring(5, 7);
            String ano = SegundaFormattedTextField1.getText().substring(0, 4);
            String nascMysql = dia+"/"+mes+"/"+ano;
            return nascMysql;
    }
        public void atualizarDataTres(){
            String dia = SegundaFormattedTextField1.getText().substring(8, 10);
            String mes = SegundaFormattedTextField1.getText().substring(5, 7);
            String ano = SegundaFormattedTextField1.getText().substring(0, 4);
            String nascMysql = dia+"/"+mes+"/"+ano;
            SegundaFormattedTextField1.setText(nascMysql);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        button1 = new java.awt.Button();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        emailTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        voltar = new javax.swing.JToggleButton();
        nomeTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        CodigoTextField2 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        nomesVacinaComboBox = new javax.swing.JComboBox<>();
        jButton6 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        CpfFormattedTextField1 = new javax.swing.JFormattedTextField();
        Cpf2FormattedTextField2 = new javax.swing.JFormattedTextField();
        CelularFormattedTextField4 = new javax.swing.JFormattedTextField();
        jLabel16 = new javax.swing.JLabel();
        NomeRuaTextField = new javax.swing.JTextField();
        UFTextField = new javax.swing.JTextField();
        CEPTextField = new javax.swing.JTextField();
        CidadeTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        BairroTextField = new javax.swing.JTextField();
        NascTextField = new javax.swing.JTextField();
        PrimeiraButton = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        SegundaButton = new javax.swing.JButton();
        SegundaFormattedTextField1 = new javax.swing.JFormattedTextField();
        PrimeiraTextField = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        CadastrosCidadãoMenuItem = new javax.swing.JMenuItem();
        CadastrarVacinaMenuItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        ConultarVacinaMenuItem = new javax.swing.JMenuItem();
        ConsultarCidadãoMenuItem = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        SairDoSistemaMenuItem = new javax.swing.JMenuItem();
        VoltarAoMenuMenuItem = new javax.swing.JMenuItem();

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Informações:");

        button1.setLabel("button1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel4.setText("CPF");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(560, 40, 27, 30);

        jButton1.setText("Consultar Cidadão");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(920, 620, 140, 35);

        jButton2.setText("Atualizar Dados");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(780, 620, 130, 35);

        jButton3.setText("Deletar Cidadão");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(640, 620, 130, 35);
        getContentPane().add(emailTextField);
        emailTextField.setBounds(510, 270, 320, 30);

        jLabel1.setText("Nome Completo");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(380, 190, 100, 30);

        jLabel2.setText("Data de Nascimento");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(380, 230, 120, 30);

        jLabel6.setText("CPF");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(380, 160, 48, 20);

        jLabel7.setText("E-mail");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(380, 280, 60, 14);

        jLabel8.setText("Telefone");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(380, 320, 60, 14);

        voltar.setText("←");
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });
        getContentPane().add(voltar);
        voltar.setBounds(20, 620, 43, 35);

        nomeTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(nomeTextField1);
        nomeTextField1.setBounds(510, 190, 320, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Informações:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(600, 80, 147, 22);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Informe o CPF para pesquisar um Paciente.");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(460, 10, 401, 22);

        jLabel5.setText("Código");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(380, 120, 70, 14);

        CodigoTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CodigoTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(CodigoTextField2);
        CodigoTextField2.setBounds(510, 110, 320, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("Cadastro de doses tomadas");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(560, 470, 295, 22);

        jLabel13.setText("Data da primeira dose");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(370, 510, 144, 14);

        jLabel14.setText("Data da segunda dose");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(370, 550, 131, 14);

        jCheckBox1.setText("Data da primeira dose");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox1);
        jCheckBox1.setBounds(290, 590, 160, 23);

        jCheckBox2.setText("Data da segunda dose");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox2);
        jCheckBox2.setBounds(460, 590, 160, 23);

        getContentPane().add(nomesVacinaComboBox);
        nomesVacinaComboBox.setBounds(810, 500, 117, 30);

        jButton6.setBackground(new java.awt.Color(0, 153, 204));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Zimagens/ConsultarCidadão.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(80, 510, 80, 80);

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel18.setText("Consultar Cidadão");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(70, 490, 130, 14);

        jButton5.setBackground(new java.awt.Color(0, 153, 204));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Zimagens/ConsultarVacina.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(80, 400, 80, 80);

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel19.setText("Consultar Vacina");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(70, 380, 120, 14);

        jButton7.setBackground(new java.awt.Color(0, 153, 204));
        jButton7.setForeground(new java.awt.Color(204, 204, 255));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Zimagens/CadastrarCidadão.png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(80, 290, 80, 80);

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel20.setText("Cadastrar Cidadão");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(70, 270, 140, 14);

        jButton4.setBackground(new java.awt.Color(0, 153, 204));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Zimagens/CadastrarVacina.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(80, 180, 80, 80);

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel21.setText("Cadastrar Vacina");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(70, 160, 130, 14);

        jLabel15.setText("Selecionar vacina");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(700, 510, 110, 14);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(810, 540, 120, 33);

        try {
            CpfFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(CpfFormattedTextField1);
        CpfFormattedTextField1.setBounds(590, 40, 180, 30);

        try {
            Cpf2FormattedTextField2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(Cpf2FormattedTextField2);
        Cpf2FormattedTextField2.setBounds(510, 150, 320, 30);

        try {
            CelularFormattedTextField4.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(CelularFormattedTextField4);
        CelularFormattedTextField4.setBounds(510, 310, 320, 30);

        jLabel16.setText("Nome da vacina aplicada");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(660, 550, 140, 14);
        getContentPane().add(NomeRuaTextField);
        NomeRuaTextField.setBounds(470, 350, 150, 30);
        getContentPane().add(UFTextField);
        UFTextField.setBounds(710, 350, 160, 30);
        getContentPane().add(CEPTextField);
        CEPTextField.setBounds(470, 390, 150, 30);
        getContentPane().add(CidadeTextField);
        CidadeTextField.setBounds(710, 390, 160, 30);

        jLabel9.setText("Nome da rua");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(380, 360, 90, 14);

        jLabel22.setText("CEP");
        getContentPane().add(jLabel22);
        jLabel22.setBounds(380, 400, 60, 14);

        jLabel23.setText("UF");
        getContentPane().add(jLabel23);
        jLabel23.setBounds(660, 360, 40, 14);

        jLabel24.setText("Cidade");
        getContentPane().add(jLabel24);
        jLabel24.setBounds(650, 400, 40, 14);
        getContentPane().add(BairroTextField);
        BairroTextField.setBounds(590, 430, 150, 30);
        getContentPane().add(NascTextField);
        NascTextField.setBounds(510, 230, 320, 30);

        PrimeiraButton.setText("Registrar primeira dose");
        PrimeiraButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrimeiraButtonActionPerformed(evt);
            }
        });
        getContentPane().add(PrimeiraButton);
        PrimeiraButton.setBounds(290, 620, 160, 30);

        jLabel25.setText("Bairro");
        getContentPane().add(jLabel25);
        jLabel25.setBounds(530, 440, 60, 14);

        SegundaButton.setText("Registrar seegunda dose");
        SegundaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SegundaButtonActionPerformed(evt);
            }
        });
        getContentPane().add(SegundaButton);
        SegundaButton.setBounds(460, 620, 170, 30);
        getContentPane().add(SegundaFormattedTextField1);
        SegundaFormattedTextField1.setBounds(500, 540, 140, 30);
        getContentPane().add(PrimeiraTextField);
        PrimeiraTextField.setBounds(500, 500, 140, 30);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Zimagens/TelaMenu2.1.png"))); // NOI18N
        jLabel17.setText("jLabel17");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(0, 0, 1070, 670);

        jMenuBar1.setBackground(new java.awt.Color(0, 51, 51));
        jMenuBar1.setForeground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMenuBar1.setPreferredSize(new java.awt.Dimension(222, 30));
        jMenuBar1.setRequestFocusEnabled(false);

        jMenu1.setBackground(new java.awt.Color(0, 51, 51));
        jMenu1.setText("Cadastrar");

        CadastrosCidadãoMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Zimagens/CadastrarCidadãoMenu.png"))); // NOI18N
        CadastrosCidadãoMenuItem.setText("Cadastrar Cidadão");
        CadastrosCidadãoMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrosCidadãoMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(CadastrosCidadãoMenuItem);

        CadastrarVacinaMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Zimagens/CadastrarVacinaMenu.png"))); // NOI18N
        CadastrarVacinaMenuItem.setText("Cadastrar Vacina");
        CadastrarVacinaMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarVacinaMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(CadastrarVacinaMenuItem);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Consultar");

        ConultarVacinaMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Zimagens/ConsultarVacinaMenu.png"))); // NOI18N
        ConultarVacinaMenuItem.setText("Consultar Vacina");
        ConultarVacinaMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConultarVacinaMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(ConultarVacinaMenuItem);

        ConsultarCidadãoMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Zimagens/ConsultarCidadãoMenu.png"))); // NOI18N
        ConsultarCidadãoMenuItem.setText("Consultar Cidadão");
        ConsultarCidadãoMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarCidadãoMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(ConsultarCidadãoMenuItem);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Realatorio");

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Zimagens/RelatorioMenu.png"))); // NOI18N
        jMenuItem2.setText("Relatorio");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuBar1.add(jMenu3);

        jMenu5.setText("Pesquisa ");

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Zimagens/calculadora.png"))); // NOI18N
        jMenuItem1.setText("Calcular data para segunda dose");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem1);

        jMenuBar1.add(jMenu5);

        jMenu4.setText("Sair");

        SairDoSistemaMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Zimagens/SairMenu.png"))); // NOI18N
        SairDoSistemaMenuItem.setText("Fechar Sistema");
        SairDoSistemaMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairDoSistemaMenuItemActionPerformed(evt);
            }
        });
        jMenu4.add(SairDoSistemaMenuItem);

        VoltarAoMenuMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Zimagens/VoltarMenu.png"))); // NOI18N
        VoltarAoMenuMenuItem.setText("Voltar ao menu");
        VoltarAoMenuMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarAoMenuMenuItemActionPerformed(evt);
            }
        });
        jMenu4.add(VoltarAoMenuMenuItem);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(1084, 734));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String nome = nomeTextField1.getText();
        String dia = NascTextField.getText().substring(0, 2);
        String mes = NascTextField.getText().substring(3, 5);
        String ano = NascTextField.getText().substring(6);
        String nasc = ano+"-"+mes+"-"+dia;
        String cpf = Cpf2FormattedTextField2.getText();
        String email = emailTextField.getText();
        String celular = CelularFormattedTextField4.getText();
        String NomeDaVacinaAplicada = (String) nomesVacinaComboBox.getSelectedItem();
        
        
        if (nomeTextField1.getText().equals("")){
        JOptionPane.showMessageDialog(null,"Insisa um nome valido.", "Algo deu errado", JOptionPane.ERROR_MESSAGE);
        return;
        }
        if (NascTextField.getText().equals("")){
        JOptionPane.showMessageDialog(null,"Insisa uma data de nacimento valido.", "Algo deu errado", JOptionPane.ERROR_MESSAGE);
        return;
        }
        if (Cpf2FormattedTextField2.getText().equals("   .   .   -  ")){
        JOptionPane.showMessageDialog(null,"Insisa um CPF valido.", "Algo deu errado", JOptionPane.ERROR_MESSAGE);
        return;
        }
        if (emailTextField.getText().equals("")){
        JOptionPane.showMessageDialog(null,"Insisa um Email valido.", "Algo deu errado", JOptionPane.ERROR_MESSAGE);
        return;
        }
        if (CelularFormattedTextField4.getText().equals("(  )      -    ")){
        JOptionPane.showMessageDialog(null,"Insisa um Numero valido.", "Algo deu errado", JOptionPane.ERROR_MESSAGE);
        return;
        }
        /*if (EndereçoTextField.getText().equals("")){
        JOptionPane.showMessageDialog(null,"Insisa uma rua valida.", "Algo deu errado", JOptionPane.ERROR_MESSAGE);
        return;
        }
        if (jFormattedTextField1.getText().equals("     -   ")){
        JOptionPane.showMessageDialog(null,"Insisa um CPF valido.", "Algo deu errado", JOptionPane.ERROR_MESSAGE);
        return;
        }
        if (CidadeTextField.getText().equals("")){
        JOptionPane.showMessageDialog(null,"Insisa uma cidade valido.", "Algo deu errado", JOptionPane.ERROR_MESSAGE);
        return;
        }
        if (BairroTextField.getText().equals("")){
        JOptionPane.showMessageDialog(null,"Insisa um bairro valido.", "Algo deu errado", JOptionPane.ERROR_MESSAGE);
        return;
        }
        if (UfComboBox.getSelectedItem().equals("Selecione a Uf")){
        JOptionPane.showMessageDialog(null,"Selecione uma Uf valido.", "Algo deu errado", JOptionPane.ERROR_MESSAGE);
        return;
        }*/
        

        Cidadão p = new Cidadão();
        p.setNome(nome);
        p.setNasc(nasc);
        p.setCpf(cpf);
        p.setEmail(email);
        p.setCelular(celular);
        //p.setPrimeiraDose(PrimeiraDose);
        //p.setSegundaDose(SegundaDose);
        p.setNomeDaVacinaAplicada(NomeDaVacinaAplicada);
        p.atualizar();
        
        PrimeiraTextField.setText("");
        NascTextField.setText("");
        CodigoTextField2.setText("");
        Cpf2FormattedTextField2.setText("");
        nomeTextField1.setText("");
        NascTextField.setText("");
        SegundaFormattedTextField1.setText("");
        emailTextField.setText("");
        CelularFormattedTextField4.setText("");
        

        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String cpf = CpfFormattedTextField1.getText();
        Cidadão p = new Cidadão();
        p.setCpf(cpf);
        p.Deletar();

        SegundaFormattedTextField1.setText("");
        jTextField1.setText("");
        CodigoTextField2.setText("");
        Cpf2FormattedTextField2.setText("");
        nomeTextField1.setText("");
        PrimeiraTextField.setText("");
        emailTextField.setText("");
        CelularFormattedTextField4.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        this.setVisible(false);
        TelaAtendente Atendente = new TelaAtendente();
        Atendente.setVisible(true);
    }//GEN-LAST:event_voltarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    String cpf = CpfFormattedTextField1.getText();
    Cidadão p = new Cidadão();
    p.setCpf(cpf);
    p = p.consulta();
    //idTextField.setText(p.getId());
    CodigoTextField2.setText(p.getCodigo());
    nomeTextField1.setText(p.getNome());
    NascTextField.setText(p.getNasc());
    atualizarData();
    Cpf2FormattedTextField2.setText(p.getCpf());
    emailTextField.setText(p.getEmail());
    CelularFormattedTextField4.setText(p.getCelular());
    PrimeiraTextField.setText(p.getPrimeiraDose());
    atualizarDataDois();
    nomesVacinaComboBox.setSelectedItem(p.getNomeDaVacinaAplicada());
    jTextField1.setText(p.getNomeDaVacinaAplicada());
    SegundaFormattedTextField1.setText(p.getSegundaDose());
    atualizarDataTres();
    NomeRuaTextField.setText(p.getRua());
    CEPTextField.setText(p.getCEP());
    UFTextField.setText(p.getUf());
    CidadeTextField.setText(p.getCidade());
    BairroTextField.setText(p.getBairro());

    
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void CodigoTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CodigoTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CodigoTextField2ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
    if (jCheckBox1.isSelected()){
        DateTimeFormatter data = DateTimeFormatter.ofLocalizedDate(FormatStyle.SHORT);
        
        LocalDateTime ldtNow = LocalDateTime.now();
        PrimeiraTextField.setText("");
        
        String format = data.format(ldtNow);
        PrimeiraTextField.setText(format);
    }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
    if (jCheckBox2.isSelected()){
        DateTimeFormatter data = DateTimeFormatter.ofLocalizedDate(FormatStyle.SHORT);
        
        LocalDateTime ldtNow = LocalDateTime.now();
        SegundaFormattedTextField1.setText("");
        
        String format = data.format(ldtNow);
        SegundaFormattedTextField1.setText(format);
    }
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void nomeTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeTextField1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
    
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        this.setVisible(false);
        TelaConsultarVacinas cadastro = new TelaConsultarVacinas();
        cadastro.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        this.setVisible(false);
        TelaCadastroCidadão cadastrar = new TelaCadastroCidadão();
        cadastrar.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.setVisible(false);
        TelaVacinas telas = new TelaVacinas();
        telas.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void CadastrosCidadãoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrosCidadãoMenuItemActionPerformed
        this.setVisible(false);
        TelaCadastroCidadão cadastro = new TelaCadastroCidadão();
        cadastro.setVisible(true);
    }//GEN-LAST:event_CadastrosCidadãoMenuItemActionPerformed

    private void CadastrarVacinaMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarVacinaMenuItemActionPerformed
        this.setVisible(false);
        TelaVacinas vacinas = new TelaVacinas();
        vacinas.setVisible(true);
    }//GEN-LAST:event_CadastrarVacinaMenuItemActionPerformed

    private void ConultarVacinaMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConultarVacinaMenuItemActionPerformed
        this.setVisible(false);
        TelaConsultarVacinas Vacina = new TelaConsultarVacinas();
        Vacina.setVisible(true);
    }//GEN-LAST:event_ConultarVacinaMenuItemActionPerformed

    private void ConsultarCidadãoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarCidadãoMenuItemActionPerformed
        this.setVisible(false);
        TelaConsultarCidadão consultar = new TelaConsultarCidadão();
        consultar.setVisible(true);
    }//GEN-LAST:event_ConsultarCidadãoMenuItemActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        this.setVisible(false);
        TelaRelatorio telas = new TelaRelatorio();
        telas.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void SairDoSistemaMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairDoSistemaMenuItemActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_SairDoSistemaMenuItemActionPerformed

    private void VoltarAoMenuMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarAoMenuMenuItemActionPerformed
        this.setVisible(false);
        TelaAtendente telas = new TelaAtendente();
        telas.setVisible(true);
    }//GEN-LAST:event_VoltarAoMenuMenuItemActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
    TelaVacinação telas = new TelaVacinação();
    telas.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void PrimeiraButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrimeiraButtonActionPerformed
        
    if (PrimeiraTextField.getText().equals("")){
        JOptionPane.showMessageDialog(null,"Adicione a data da primeira dose para continuar.", "Algo deu errado", JOptionPane.ERROR_MESSAGE);
        return;
        }
    
    String dia1 = PrimeiraTextField.getText().substring(0, 2);
    String mes1 = PrimeiraTextField.getText().substring(3, 5);
    String ano1 = PrimeiraTextField.getText().substring(6);
    String PrimeiraDose = ano1+"-"+mes1+"-"+dia1;
    String cpf = Cpf2FormattedTextField2.getText();

    Cidadão p = new Cidadão();
    p.setPrimeiraDose(PrimeiraDose);
    p.setCpf(cpf);
    p.atualizarDose1();
    
    String NomeDaVacinaAplicada = (String) nomesVacinaComboBox.getSelectedItem();
    p.setNomeDaVacinaAplicada(NomeDaVacinaAplicada);
    p.atualizarNome1();
    }//GEN-LAST:event_PrimeiraButtonActionPerformed

    private void SegundaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SegundaButtonActionPerformed
    if (SegundaFormattedTextField1.getText().equals("")){
        JOptionPane.showMessageDialog(null,"Adicione a data da segunda dose para continuar.", "Algo deu errado", JOptionPane.ERROR_MESSAGE);
        return;
        }
    
    String dia2 = SegundaFormattedTextField1.getText().substring(0, 2);
    String mes2 = SegundaFormattedTextField1.getText().substring(3, 5);
    String ano2 = SegundaFormattedTextField1.getText().substring(6);
    String SegundaDose = ano2+"-"+mes2+"-"+dia2;
    String cpf = Cpf2FormattedTextField2.getText();
    
    Cidadão p = new Cidadão();
    p.setSegundaDose(SegundaDose);
    p.setCpf(cpf);
    p.atualizarDose2();
    }//GEN-LAST:event_SegundaButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaConsultarCidadão.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaConsultarCidadão.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaConsultarCidadão.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaConsultarCidadão.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaConsultarCidadão().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BairroTextField;
    private javax.swing.JTextField CEPTextField;
    private javax.swing.JMenuItem CadastrarVacinaMenuItem;
    private javax.swing.JMenuItem CadastrosCidadãoMenuItem;
    private javax.swing.JFormattedTextField CelularFormattedTextField4;
    private javax.swing.JTextField CidadeTextField;
    private javax.swing.JTextField CodigoTextField2;
    private javax.swing.JMenuItem ConsultarCidadãoMenuItem;
    private javax.swing.JMenuItem ConultarVacinaMenuItem;
    private javax.swing.JFormattedTextField Cpf2FormattedTextField2;
    private javax.swing.JFormattedTextField CpfFormattedTextField1;
    private javax.swing.JTextField NascTextField;
    private javax.swing.JTextField NomeRuaTextField;
    private javax.swing.JButton PrimeiraButton;
    private javax.swing.JTextField PrimeiraTextField;
    private javax.swing.JMenuItem SairDoSistemaMenuItem;
    private javax.swing.JButton SegundaButton;
    private javax.swing.JFormattedTextField SegundaFormattedTextField1;
    private javax.swing.JTextField UFTextField;
    private javax.swing.JMenuItem VoltarAoMenuMenuItem;
    private java.awt.Button button1;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField nomeTextField1;
    private javax.swing.JComboBox<String> nomesVacinaComboBox;
    private javax.swing.JToggleButton voltar;
    // End of variables declaration//GEN-END:variables
private void setIcon() {
       setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Zimagens/unnamed.png")));
    }
}
