/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Cidadão;

import Cidadão.Cidadão;
import Atendente.TelaAtendente;
import Atendente.TelaRelatorio;
import Atendente.loginAtendente;
import Vacina.TelaConsultarVacinas;
import Vacina.TelaVacinas;
import java.awt.Color;
import javax.swing.JOptionPane;
import Vacina.Vacina;
import java.awt.Toolkit;

/**
 *
 * @author Oliveira
 */
public class TelaCadastroCidadão extends javax.swing.JFrame {
    
    /**
     * Creates new form TelaCadastro
     */
    public TelaCadastroCidadão() {
    initComponents();
    CadastrosCidadãoMenuItem.setEnabled(false);
    jButton7.setEnabled(false);
    setIcon();
    CadastrosCidadãoMenuItem.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jMenuItem1 = new javax.swing.JMenuItem();
        jColorChooser1 = new javax.swing.JColorChooser();
        botaoCadastrar = new javax.swing.JButton();
        emailTextField = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        voltar = new javax.swing.JToggleButton();
        nomeTextField = new javax.swing.JTextField();
        EndereçoTextField = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        CidadeTextField = new javax.swing.JTextField();
        BairroTextField = new javax.swing.JTextField();
        LimparButton = new javax.swing.JButton();
        DataDeNacimentoFormattedTextField = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        CPFFormattedTextField = new javax.swing.JFormattedTextField();
        TelefoneFormattedTextField = new javax.swing.JFormattedTextField();
        UfComboBox = new javax.swing.JComboBox<>();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        CadastrosCidadãoMenuItem = new javax.swing.JMenuItem();
        CadastrarVacinaMenuItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        ConultarVacinaMenuItem = new javax.swing.JMenuItem();
        ConsultarCidadãoMenuItem = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        SairDoSistemaMenuItem = new javax.swing.JMenuItem();
        VoltarAoMenuMenuItem = new javax.swing.JMenuItem();

        jPasswordField1.setText("jPasswordField1");
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        botaoCadastrar.setBackground(new java.awt.Color(0, 102, 204));
        botaoCadastrar.setForeground(new java.awt.Color(255, 255, 255));
        botaoCadastrar.setText("Cadastrar");
        botaoCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(botaoCadastrar);
        botaoCadastrar.setBounds(860, 565, 120, 60);

        emailTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailTextFieldFocusGained(evt);
            }
        });
        getContentPane().add(emailTextField);
        emailTextField.setBounds(490, 270, 200, 30);

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel21.setText("Insira as informações abaixo");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(460, 10, 306, 29);

        voltar.setBackground(new java.awt.Color(102, 255, 255));
        voltar.setText("←");
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });
        getContentPane().add(voltar);
        voltar.setBounds(10, 620, 50, 23);

        nomeTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nomeTextFieldFocusGained(evt);
            }
        });
        nomeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(nomeTextField);
        nomeTextField.setBounds(490, 90, 240, 30);

        EndereçoTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                EndereçoTextFieldFocusGained(evt);
            }
        });
        getContentPane().add(EndereçoTextField);
        EndereçoTextField.setBounds(490, 390, 200, 30);

        jButton6.setBackground(new java.awt.Color(0, 153, 204));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Zimagens/ConsultarCidadão.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(90, 500, 80, 80);

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel18.setText("Consultar Cidadão");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(80, 480, 130, 14);

        jButton5.setBackground(new java.awt.Color(0, 153, 204));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Zimagens/ConsultarVacina.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(90, 390, 80, 80);

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel19.setText("Consultar Vacina");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(80, 370, 120, 14);

        jButton7.setBackground(new java.awt.Color(0, 153, 204));
        jButton7.setForeground(new java.awt.Color(204, 204, 255));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Zimagens/CadastrarCidadão.png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(90, 280, 80, 80);

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel20.setText("Cadastrar Cidadão");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(80, 260, 140, 14);

        jButton4.setBackground(new java.awt.Color(0, 153, 204));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Zimagens/CadastrarVacina.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(90, 170, 80, 80);

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel22.setText("Cadastrar Vacina");
        getContentPane().add(jLabel22);
        jLabel22.setBounds(80, 150, 130, 14);

        CidadeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CidadeTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(CidadeTextField);
        CidadeTextField.setBounds(490, 510, 130, 30);
        getContentPane().add(BairroTextField);
        BairroTextField.setBounds(630, 510, 130, 30);

        LimparButton.setText("Limpar");
        LimparButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimparButtonActionPerformed(evt);
            }
        });
        getContentPane().add(LimparButton);
        LimparButton.setBounds(630, 570, 130, 30);

        try {
            DataDeNacimentoFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(DataDeNacimentoFormattedTextField);
        DataDeNacimentoFormattedTextField.setBounds(490, 150, 100, 30);

        jLabel2.setText("Nome completo");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(490, 60, 130, 30);

        jLabel3.setText("UF");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(490, 540, 60, 30);

        jLabel5.setText("Digite o e-mail ");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(490, 240, 130, 30);

        jLabel6.setText("DIgite o telefone");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(490, 300, 130, 30);

        jLabel7.setText("Rua da rua");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(490, 360, 130, 30);

        jLabel8.setText("CEP da residencia");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(490, 420, 130, 30);

        jLabel9.setText("Cidade");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(490, 480, 130, 30);

        jLabel11.setText("Bairro");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(630, 480, 130, 30);

        jLabel12.setText("Digite o cpf");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(490, 180, 130, 30);

        jLabel13.setText("Data de nacimento");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(490, 120, 130, 30);

        try {
            CPFFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(CPFFormattedTextField);
        CPFFormattedTextField.setBounds(490, 210, 130, 30);

        try {
            TelefoneFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        TelefoneFormattedTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelefoneFormattedTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(TelefoneFormattedTextField);
        TelefoneFormattedTextField.setBounds(490, 330, 200, 30);

        UfComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione a Uf", "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        getContentPane().add(UfComboBox);
        UfComboBox.setBounds(490, 570, 130, 30);

        try {
            jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(jFormattedTextField1);
        jFormattedTextField1.setBounds(490, 450, 130, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Zimagens/TelaMenu2.1.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1040, 660);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(500, 220, 240, 20);

        jTextField2.setText("jTextField2");
        getContentPane().add(jTextField2);
        jTextField2.setBounds(530, 110, 60, 20);

        jMenuBar1.setBackground(new java.awt.Color(0, 51, 51));
        jMenuBar1.setForeground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMenuBar1.setPreferredSize(new java.awt.Dimension(222, 30));
        jMenuBar1.setRequestFocusEnabled(false);

        jMenu1.setBackground(new java.awt.Color(0, 51, 51));
        jMenu1.setText("Cadastrar");

        CadastrosCidadãoMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Zimagens/CadastrarCidadãoMenu.png"))); // NOI18N
        CadastrosCidadãoMenuItem.setText("Cadastrar Cidadão");
        CadastrosCidadãoMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrosCidadãoMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(CadastrosCidadãoMenuItem);

        CadastrarVacinaMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Zimagens/CadastrarVacinaMenu.png"))); // NOI18N
        CadastrarVacinaMenuItem.setText("Cadastrar Vacina");
        CadastrarVacinaMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarVacinaMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(CadastrarVacinaMenuItem);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Consultar");

        ConultarVacinaMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Zimagens/ConsultarVacinaMenu.png"))); // NOI18N
        ConultarVacinaMenuItem.setText("Consultar Vacina");
        ConultarVacinaMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConultarVacinaMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(ConultarVacinaMenuItem);

        ConsultarCidadãoMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Zimagens/ConsultarCidadãoMenu.png"))); // NOI18N
        ConsultarCidadãoMenuItem.setText("Consultar Cidadão");
        ConsultarCidadãoMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarCidadãoMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(ConsultarCidadãoMenuItem);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Realatorio");

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Zimagens/RelatorioMenu.png"))); // NOI18N
        jMenuItem2.setText("Relatorio");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Sair");

        SairDoSistemaMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Zimagens/SairMenu.png"))); // NOI18N
        SairDoSistemaMenuItem.setText("Fechar Sistema");
        SairDoSistemaMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairDoSistemaMenuItemActionPerformed(evt);
            }
        });
        jMenu4.add(SairDoSistemaMenuItem);

        VoltarAoMenuMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Zimagens/VoltarMenu.png"))); // NOI18N
        VoltarAoMenuMenuItem.setText("Voltar ao menu");
        VoltarAoMenuMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarAoMenuMenuItemActionPerformed(evt);
            }
        });
        jMenu4.add(VoltarAoMenuMenuItem);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(1055, 725));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void botaoCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastrarActionPerformed
       // cadastro do cidadão
       String nome = nomeTextField.getText();
       String dia = DataDeNacimentoFormattedTextField.getText().substring(0, 2);
       String mes = DataDeNacimentoFormattedTextField.getText().substring(3, 5);
       String ano = DataDeNacimentoFormattedTextField.getText().substring(6);
       String nasc = ano+"-"+mes+"-"+dia;
       String cpf = CPFFormattedTextField.getText();
       String email = emailTextField.getText();
       String celular = TelefoneFormattedTextField.getText();
       //cadastros do endereço do cidadão.          
       String rua = EndereçoTextField.getText();
       String CEP = jFormattedTextField1.getText();
       String cidade = CidadeTextField.getText();
       String bairro = BairroTextField.getText();
       String uf = (String) UfComboBox.getSelectedItem();
       
      
        if (nomeTextField.getText().equals("")){
        JOptionPane.showMessageDialog(null,"Insisa um nome valido.", "Algo deu errado", JOptionPane.ERROR_MESSAGE);
        return;
        }
        if (DataDeNacimentoFormattedTextField.getText().equals("  /  /    ")){
        JOptionPane.showMessageDialog(null,"Insisa uma data de nacimento valido.", "Algo deu errado", JOptionPane.ERROR_MESSAGE);
        return;
        }
        if (CPFFormattedTextField.getText().equals("   .   .   -  ")){
        JOptionPane.showMessageDialog(null,"Insisa um CPF valido.", "Algo deu errado", JOptionPane.ERROR_MESSAGE);
        return;
        }
        if (emailTextField.getText().equals("")){
        JOptionPane.showMessageDialog(null,"Insisa um Email valido.", "Algo deu errado", JOptionPane.ERROR_MESSAGE);
        return;
        }
        if (TelefoneFormattedTextField.getText().equals("(  )      -    ")){
        JOptionPane.showMessageDialog(null,"Insisa um Numero valido.", "Algo deu errado", JOptionPane.ERROR_MESSAGE);
        return;
        }
        if (EndereçoTextField.getText().equals("")){
        JOptionPane.showMessageDialog(null,"Insisa uma rua valida.", "Algo deu errado", JOptionPane.ERROR_MESSAGE);
        return;
        }
        if (jFormattedTextField1.getText().equals("     -   ")){
        JOptionPane.showMessageDialog(null,"Insisa um CPF valido.", "Algo deu errado", JOptionPane.ERROR_MESSAGE);
        return;
        }
        if (CidadeTextField.getText().equals("")){
        JOptionPane.showMessageDialog(null,"Insisa uma cidade valido.", "Algo deu errado", JOptionPane.ERROR_MESSAGE);
        return;
        }
        if (BairroTextField.getText().equals("")){
        JOptionPane.showMessageDialog(null,"Insisa um bairro valido.", "Algo deu errado", JOptionPane.ERROR_MESSAGE);
        return;
        }
        if (UfComboBox.getSelectedItem().equals("Selecione a Uf")){
        JOptionPane.showMessageDialog(null,"Selecione uma Uf valido.", "Algo deu errado", JOptionPane.ERROR_MESSAGE);
        return;
        }
        

        
        //menssagem se o cidadão ja existe. 
        try{
        MenssagemDeErro atendente = new MenssagemDeErro(cpf);
        if(atendente.existe(atendente)){
        JOptionPane.showMessageDialog(null,"Cidadão ja castrado.", "Algo deu errado", JOptionPane.ERROR_MESSAGE);
        }else {
        JOptionPane.showMessageDialog(null, "O usuario foi cadastrado com sucesso");
        Cidadão p = new Cidadão ();
        
        
        
        p.setNome(nome);
        p.setCpf(cpf);
        p.setEmail(email);
        p.setCelular(celular);
        p.setNasc(nasc);
        p.setPrimeiraDose(null);
        p.setSegundaDose(null);
        p.setRua(rua);
        p.setCEP(CEP);
        p.setCidade(cidade);
        p.setBairro(bairro);
        p.setUf(uf);
        p.inserir();

    //idTextField.setText(p.getId());
    nomeTextField.getText();
    DataDeNacimentoFormattedTextField.setText(p.getNasc());
    CPFFormattedTextField.setText(p.getCpf());
    emailTextField.setText(p.getEmail());
    TelefoneFormattedTextField.setText(p.getCelular());
        }
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, "Problemas tecnicos. Tente novamente mais tarde");
        e.printStackTrace();
    }

    }//GEN-LAST:event_botaoCadastrarActionPerformed

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        this.setVisible(false);
        TelaAtendente Atendente = new TelaAtendente();
        Atendente.setVisible(true);
    }//GEN-LAST:event_voltarActionPerformed

    private void nomeTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nomeTextFieldFocusGained

    }//GEN-LAST:event_nomeTextFieldFocusGained

    private void emailTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailTextFieldFocusGained

    }//GEN-LAST:event_emailTextFieldFocusGained

    private void nomeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeTextFieldActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        this.setVisible(false);
        TelaConsultarCidadão cadastro = new TelaConsultarCidadão();
        cadastro.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        this.setVisible(false);
        TelaConsultarVacinas cadastro = new TelaConsultarVacinas();
        cadastro.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed

    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.setVisible(false);
        TelaVacinas telas = new TelaVacinas();
        telas.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void LimparButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimparButtonActionPerformed
    nomeTextField.setText("");
    DataDeNacimentoFormattedTextField.setText("");
    CPFFormattedTextField.setText("");
    emailTextField.setText("");
    TelefoneFormattedTextField.setText("");
    EndereçoTextField.setText("");
    jFormattedTextField1.setText("");
    CidadeTextField.setText("");
    BairroTextField.setText("");
    UfComboBox.setSelectedItem("Selecione a Uf");
    }//GEN-LAST:event_LimparButtonActionPerformed

    private void EndereçoTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EndereçoTextFieldFocusGained

    }//GEN-LAST:event_EndereçoTextFieldFocusGained

    private void CidadeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CidadeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CidadeTextFieldActionPerformed

    private void TelefoneFormattedTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelefoneFormattedTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TelefoneFormattedTextFieldActionPerformed

    private void CadastrosCidadãoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrosCidadãoMenuItemActionPerformed
        this.setVisible(false);
        TelaCadastroCidadão cadastro = new TelaCadastroCidadão();
        cadastro.setVisible(true);
    }//GEN-LAST:event_CadastrosCidadãoMenuItemActionPerformed

    private void CadastrarVacinaMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarVacinaMenuItemActionPerformed
        this.setVisible(false);
        TelaVacinas vacinas = new TelaVacinas();
        vacinas.setVisible(true);
    }//GEN-LAST:event_CadastrarVacinaMenuItemActionPerformed

    private void ConultarVacinaMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConultarVacinaMenuItemActionPerformed
        this.setVisible(false);
        TelaConsultarVacinas Vacina = new TelaConsultarVacinas();
        Vacina.setVisible(true);
    }//GEN-LAST:event_ConultarVacinaMenuItemActionPerformed

    private void ConsultarCidadãoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarCidadãoMenuItemActionPerformed
        this.setVisible(false);
        TelaConsultarCidadão consultar = new TelaConsultarCidadão();
        consultar.setVisible(true);
    }//GEN-LAST:event_ConsultarCidadãoMenuItemActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        this.setVisible(false);
        TelaRelatorio telas = new TelaRelatorio();
        telas.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void SairDoSistemaMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairDoSistemaMenuItemActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_SairDoSistemaMenuItemActionPerformed

    private void VoltarAoMenuMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarAoMenuMenuItemActionPerformed
        this.setVisible(false);
        TelaAtendente telas = new TelaAtendente();
        telas.setVisible(true);
    }//GEN-LAST:event_VoltarAoMenuMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroCidadão.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroCidadão.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroCidadão.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroCidadão.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroCidadão().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BairroTextField;
    private javax.swing.JFormattedTextField CPFFormattedTextField;
    private javax.swing.JMenuItem CadastrarVacinaMenuItem;
    private javax.swing.JMenuItem CadastrosCidadãoMenuItem;
    private javax.swing.JTextField CidadeTextField;
    private javax.swing.JMenuItem ConsultarCidadãoMenuItem;
    private javax.swing.JMenuItem ConultarVacinaMenuItem;
    private javax.swing.JFormattedTextField DataDeNacimentoFormattedTextField;
    private javax.swing.JTextField EndereçoTextField;
    private javax.swing.JButton LimparButton;
    private javax.swing.JMenuItem SairDoSistemaMenuItem;
    private javax.swing.JFormattedTextField TelefoneFormattedTextField;
    private javax.swing.JComboBox<String> UfComboBox;
    private javax.swing.JMenuItem VoltarAoMenuMenuItem;
    private javax.swing.JButton botaoCadastrar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField nomeTextField;
    private javax.swing.JToggleButton voltar;
    // End of variables declaration//GEN-END:variables
private void setIcon() {
       setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Zimagens/unnamed.png")));
    }
}
