/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ABProjeto;

import Administrador.LoginAdministrador;
import Administrador.TelaAdministrador;
import Atendente.Atendente;
import Atendente.Atendente;
import Atendente.TelaAtendente;
import Atendente.TelaAtendente;
import Atendente.loginAtendente;
import javax.swing.JOptionPane;
import java.awt.Desktop;
import java.awt.Toolkit;
import java.net.URI;

/**
 *
 * @author Oliveira
 */
public class TelaLogin extends javax.swing.JFrame {

    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        initComponents();
        setIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginTextField = new javax.swing.JTextField();
        loginButton = new javax.swing.JButton();
        loginJLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        senhaJLabel = new javax.swing.JLabel();
        senhaPasswordField = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        ComboBox = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(280, 330));
        getContentPane().setLayout(null);

        loginTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(loginTextField);
        loginTextField.setBounds(250, 250, 120, 30);

        loginButton.setBackground(new java.awt.Color(0, 102, 204));
        loginButton.setForeground(new java.awt.Color(255, 255, 255));
        loginButton.setText("Entrar");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        getContentPane().add(loginButton);
        loginButton.setBounds(250, 390, 120, 30);

        loginJLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        loginJLabel.setText("Login");
        getContentPane().add(loginJLabel);
        loginJLabel.setBounds(200, 260, 40, 17);

        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(250, 230, 160, 20);

        senhaJLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        senhaJLabel.setText("Senha");
        getContentPane().add(senhaJLabel);
        senhaJLabel.setBounds(200, 300, 50, 17);

        senhaPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senhaPasswordFieldActionPerformed(evt);
            }
        });
        getContentPane().add(senhaPasswordField);
        senhaPasswordField.setBounds(250, 290, 120, 30);

        jButton1.setBackground(new java.awt.Color(51, 153, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("covid.saude.gov.br");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(580, 380, 160, 40);

        ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione um Usuario", "Administrador", "Atendente" }));
        getContentPane().add(ComboBox);
        ComboBox.setBounds(230, 350, 160, 30);

        jButton2.setText("Atendente");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(600, 320, 110, 23);

        jButton3.setText("Administrador");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(600, 350, 110, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Zimagens/TelaLogin.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 960, 560);

        setSize(new java.awt.Dimension(973, 594));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loginTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginTextFieldActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
    if (ComboBox.getSelectedItem().equals("Selecione um Usuario")){
          JOptionPane.showMessageDialog(null, "Selecione um usuario valido para contunuar", "Algo deu errado", JOptionPane.ERROR_MESSAGE);
      }
    
    if (ComboBox.getSelectedItem().equals("Atendente")){
    String nome = loginTextField.getText();
    String senha = new String(senhaPasswordField.getPassword());
    try{
        loginAtendente atendente = new loginAtendente(nome, senha);
        if(atendente.existe(atendente)){
            this.setVisible(false);
            TelaAtendente telas = new TelaAtendente();
            telas.setVisible(true);
        }
        else { jLabel2.setText("Login ou Senha errada");
      }
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, "Problemas tecnicos. Tente novamente mais tarde");
        e.printStackTrace();
    }
    }
    
    if (ComboBox.getSelectedItem().equals("Administrador")){
    String nome = loginTextField.getText();
    String senha = new String(senhaPasswordField.getPassword());
    try{
        LoginAdministrador administrador = new LoginAdministrador(nome, senha);
        if(administrador.existe(administrador)){
            this.setVisible(false);
            TelaAdministrador telas = new TelaAdministrador();
            telas.setVisible(true);
        }
        else { jLabel2.setText("Login ou Senha errada");
      }
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, "Problemas tecnicos. Tente novamente mais tarde");
        e.printStackTrace();
    }
    }
    }//GEN-LAST:event_loginButtonActionPerformed

    private void senhaPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senhaPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_senhaPasswordFieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    try{
        URI link = new URI("https://covid.saude.gov.br");
        Desktop.getDesktop().browse(link);
    }catch(Exception erro){
        System.out.println(erro);
    }
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    this.setVisible(false);
            TelaAtendente telas = new TelaAtendente();
            telas.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    this.setVisible(false);
            TelaAdministrador telas = new TelaAdministrador();
            telas.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel loginJLabel;
    private javax.swing.JTextField loginTextField;
    private javax.swing.JLabel senhaJLabel;
    private javax.swing.JPasswordField senhaPasswordField;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
       setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Zimagens/unnamed.png")));
    }
}
